(()=>{'use strict';
const CFG=window.MPK_CONFIG,ROSTER=window.MPK_ROSTER,DATA=window.MPK_DATA,$=id=>document.getElementById(id);
const state={user:null,participant:null,category:null,scores:{},attendance:null,deferredInstall:null};
const LS='mpkpmb29_assessments';
const getAll=()=>JSON.parse(localStorage.getItem(LS)||'[]');
const saveAll=a=>localStorage.setItem(LS,JSON.stringify(a));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m){const e=$('toast');e.textContent=m;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2300)}
function cloudReady(){return !!(CFG.SUPABASE_URL&&(CFG.SUPABASE_PUBLISHABLE_KEY||CFG.SUPABASE_ANON_KEY))}
function scoreClass(v){if(v==null)return's-none';if(v<5)return's-red';if(v<7)return's-yellow';if(v<9)return's-green';return's-blue'}
function recommendation(s){const map={pbb:'PBB',discipline:'Disiplin Waktu',computer:'Komputer/Laptop',scientific:'Karya Ilmiah',ppkk:'PPKK'},arr=Object.entries(map).map(([k,l])=>({k,l,v:s[k]})).filter(x=>x.v!=null).sort((a,b)=>a.v-b.v);if(!arr.length)return'Belum ada data. Lakukan asesmen baseline.';const low=arr.filter(x=>x.v<7);if(low.length)return low.map(x=>`${x.l}: ${x.v<3?'intervensi intensif':x.v<5?'pembinaan khusus':'latihan tambahan'}`).join(' • ');const m=arr.filter(x=>x.v>=9).map(x=>x.l);return m.length?`Kompeten; kandidat peer mentor pada ${m.join(', ')}.`:'Capaian kompeten. Pertahankan dan lakukan pengayaan.'}
function overall(s){const vals=Object.values(s).filter(v=>v!=null);if(!vals.length)return'Belum dinilai';const lows=vals.filter(v=>v<7).length;if(vals.some(v=>v<3)||lows>=3)return'Intervensi';if(lows===2)return'Pembinaan';if(lows===1)return'Penguatan';if(vals.length<5)return'Data belum lengkap';return'Aman'}
function summaries(){const all=getAll(),out=ROSTER.map(p=>({participant:p,scores:{}}));for(const x of out){for(const k of Object.keys(DATA.categories)){const rows=all.filter(a=>a.participant_id===x.participant.id&&a.category===k&&a.final_score!=null).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));if(!rows.length)continue;x.scores[k]=k==='discipline'?rows.reduce((s,r)=>s+Number(r.final_score),0)/rows.length:Number(rows.at(-1).final_score)}}return{all,summary:out}}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='dashboardView')renderDashboard();if(id==='historyView')renderHistory();if(id==='adminView')renderStatus()}
function loginDemo(){state.user={name:$('demoName').value.trim()||'Pembina MPK-PMB',role:$('demoRole').value};localStorage.setItem('mpkpmb29_user',JSON.stringify(state.user));enterApp()}
function enterApp(){if(!state.user)return;$('loginScreen').classList.add('hidden');$('appShell').classList.remove('hidden');const c=state.user.role==='coordinator';$('userLabel').textContent=`${state.user.name} • ${c?'Koordinator':'Penilai'}`;document.querySelector('[data-view="dashboardView"]').classList.toggle('hidden',!c);document.querySelector('[data-view="adminView"]').classList.toggle('hidden',!c);$('onlineBadge').textContent=navigator.onLine?'Online':'Offline';$('onlineBadge').classList.toggle('online',navigator.onLine);showView(c?'dashboardView':'assessmentView')}
function logout(){localStorage.removeItem('mpkpmb29_user');location.reload()}
function findParticipant(){const n=parseInt($('participantNo').value,10),p=ROSTER.find(x=>x.id===n);if(!p){$('participantCard').className='participant-card empty';$('participantCard').textContent='Nomor harus 01–80.';$('assessmentControls').classList.add('hidden');return}state.participant=p;$('participantNo').value=p.code;const prof=summaries().summary.find(x=>x.participant.id===p.id);$('participantCard').className='participant-card';$('participantCard').innerHTML=`<div class="row"><div class="code">${p.code}</div><div><div class="name">${esc(p.name)}</div><span class="program">${p.program}</span></div></div><div style="margin-top:11px;padding-top:10px;border-top:1px solid #dfe7ef;font-size:12px"><strong>Rekomendasi:</strong><br>${esc(recommendation(prof.scores))}</div>`;$('assessmentControls').classList.remove('hidden');$('rubricPanel').classList.add('hidden');document.querySelectorAll('.category-btn').forEach(b=>b.classList.remove('active'))}
function renderCategoryButtons(){const b=$('categoryButtons');b.innerHTML='';Object.entries(DATA.categories).forEach(([k,c])=>{const x=document.createElement('button');x.className='category-btn';x.innerHTML=`<span>${c.icon}</span><small>${esc(c.label)}</small>`;x.onclick=()=>{state.category=k;state.scores={};state.attendance=null;document.querySelectorAll('.category-btn').forEach(y=>y.classList.remove('active'));x.classList.add('active');renderRubric()};b.appendChild(x)})}
function saveBlock(){return`<label>Catatan Pembina <small style="font-weight:500;color:#64748b">(opsional)</small></label><textarea id="assessmentNotes" rows="3" placeholder="Catatan koreksi/kebutuhan pembinaan..."></textarea><div class="save-row"><button id="saveAssessmentBtn" class="primary">Simpan Penilaian</button></div>`}
function renderRubric(){const c=DATA.categories[state.category],box=$('rubricPanel');box.classList.remove('hidden');if(c.special==='attendance'){box.innerHTML=`<div class="panel-head"><h3>${c.icon} ${c.label}</h3><div class="score-preview" id="scorePreview">—</div></div><div class="attendance-grid">${c.statuses.map(s=>`<button class="attendance-btn" data-key="${s.key}"><strong>${esc(s.label)}</strong><br><small>${s.score==null?'I/S – tidak dihitung':`Skor ${s.score}`}</small></button>`).join('')}</div>${saveBlock()}`;box.querySelectorAll('.attendance-btn').forEach(b=>b.onclick=()=>{box.querySelectorAll('.attendance-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.attendance=b.dataset.key;const s=c.statuses.find(x=>x.key===state.attendance);$('scorePreview').textContent=s.score==null?'I/S':s.score.toFixed(1)});$('saveAssessmentBtn').onclick=saveAssessment;return}
box.innerHTML=`<div class="panel-head"><h3>${c.icon} ${c.label}</h3><div class="score-preview" id="scorePreview">—</div></div>${c.indicators.map(i=>`<div class="rubric-item"><div class="rubric-title">${esc(i.label)} <small>(${i.weight}%)</small></div><div class="rubric-hint">${esc(i.hint)}</div><div class="score-buttons" data-ind="${i.key}">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button class="score-btn" data-score="${n}" title="${esc(DATA.scoreGuide[n])}">${n}</button>`).join('')}</div><div class="score-help" id="help-${i.key}"></div></div>`).join('')}${saveBlock()}`;box.querySelectorAll('.score-buttons').forEach(g=>g.querySelectorAll('.score-btn').forEach(b=>b.onclick=()=>{g.querySelectorAll('.score-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.scores[g.dataset.ind]=Number(b.dataset.score);$(`help-${g.dataset.ind}`).textContent=DATA.scoreGuide[b.dataset.score];updatePreview()}));$('saveAssessmentBtn').onclick=saveAssessment}
function calcScore(){const c=DATA.categories[state.category];if(c.special==='attendance'){const s=c.statuses.find(x=>x.key===state.attendance);return s?s.score:null}if(c.indicators.some(i=>state.scores[i.key]==null))return null;return c.indicators.reduce((s,i)=>s+state.scores[i.key]*i.weight/100,0)}
function updatePreview(){const v=calcScore();$('scorePreview').textContent=v==null?'—':v.toFixed(1)}
function saveAssessment(){if(!state.participant||!state.category)return;const c=DATA.categories[state.category];if(c.special==='attendance'&&!state.attendance)return toast('Pilih status disiplin.');if(!c.special&&c.indicators.some(i=>state.scores[i.key]==null))return toast('Semua indikator harus diberi skor.');const v=calcScore(),all=getAll();all.push({id:Date.now()+'-'+Math.random().toString(16).slice(2),participant_id:state.participant.id,code:state.participant.code,name:state.participant.name,program:state.participant.program,category:state.category,activity:$('activitySelect').value,scores:{...state.scores},final_score:v,discipline_status:state.attendance,notes:$('assessmentNotes').value.trim(),assessor_name:state.user.name,created_at:new Date().toISOString(),synced:false});saveAll(all);toast(`Tersimpan: ${state.participant.code} • ${c.label}${v==null?'':` • ${v.toFixed(1)}`}`);renderRubric();renderDashboard();renderHistory()}
function renderDashboard(){const {all,summary}=summaries(),pf=$('programFilter').value||'ALL',list=summary.filter(x=>pf==='ALL'||x.participant.program===pf),assessed=list.filter(x=>Object.values(x.scores).length).length,attention=list.filter(x=>['Intervensi','Pembinaan','Penguatan'].includes(overall(x.scores))).length;$('statsGrid').innerHTML=`<div class="stat"><div class="n">${list.length}</div><div class="l">Peserta</div></div><div class="stat"><div class="n">${assessed}</div><div class="l">Sudah memiliki nilai</div></div><div class="stat attn"><div class="n">${attention}</div><div class="l">Perlu perhatian</div></div><div class="stat pending"><div class="n">${all.filter(x=>!x.synced).length}</div><div class="l">Data lokal</div></div>`;const box=$('participantSummary');box.innerHTML=`<div class="participant-row header"><div>No.</div><div>Nama</div><div>PBB</div><div>Disiplin</div><div>Komputer</div><div>Ilmiah</div><div>PPKK</div><div>Status</div></div>`+list.map(x=>`<div class="participant-row" data-pid="${x.participant.id}"><div><strong>${x.participant.code}</strong></div><div><div class="pname">${esc(x.participant.name)}</div><small>${x.participant.program}</small></div>${['pbb','discipline','computer','scientific','ppkk'].map(k=>`<div><span class="score-pill ${scoreClass(x.scores[k])}">${x.scores[k]==null?'—':x.scores[k].toFixed(1)}</span></div>`).join('')}<div>${overall(x.scores)}</div></div>`).join('');box.querySelectorAll('[data-pid]').forEach(r=>r.onclick=()=>{showView('assessmentView');$('participantNo').value=String(r.dataset.pid).padStart(2,'0');findParticipant()})}
function renderHistory(){let rows=getAll().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)),n=parseInt($('historyNo').value,10),cat=$('historyCategory').value;if(n)rows=rows.filter(x=>x.participant_id===n);if(cat&&cat!=='ALL')rows=rows.filter(x=>x.category===cat);$('historyList').innerHTML=rows.slice(0,200).map(a=>`<div class="history-card"><div class="top"><div><strong>${a.code} • ${esc(a.name)}</strong><br><small>${a.program} • ${esc(DATA.categories[a.category].label)} • ${esc(a.activity)}</small></div><div class="score">${a.final_score==null?'I/S':Number(a.final_score).toFixed(1)}</div></div><small>${new Date(a.created_at).toLocaleString('id-ID')} • Penilai: ${esc(a.assessor_name)}</small>${a.notes?`<div style="margin-top:8px;font-size:13px">${esc(a.notes)}</div>`:''}</div>`).join('')||'<div class="panel">Belum ada riwayat.</div>'}
function renderStatus(){const all=getAll();$('systemStatus').innerHTML=`<div class="system-item"><span>Mode</span><strong>${cloudReady()?'Siap Cloud':'Demo lokal'}</strong></div><div class="system-item"><span>Internet</span><strong>${navigator.onLine?'Online':'Offline'}</strong></div><div class="system-item"><span>Total penilaian</span><strong>${all.length}</strong></div><div class="system-item"><span>Pengguna</span><strong>${esc(state.user?.name||'-')}</strong></div>`}
function exportCSV(){const all=getAll(),h=['nomor','nama','prodi','bidang','kegiatan','nilai','penilai','tanggal','catatan'],lines=[h.join(',')];all.forEach(a=>lines.push([a.code,a.name,a.program,DATA.categories[a.category].label,a.activity,a.final_score??'',a.assessor_name,a.created_at,a.notes||''].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')));const b=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='MPKPMB_XXIX.csv';a.click();URL.revokeObjectURL(u)}
function init(){DATA.activities.forEach(x=>$('activitySelect').add(new Option(x,x)));Object.entries(DATA.categories).forEach(([k,c])=>$('historyCategory').add(new Option(c.label,k)));renderCategoryButtons();$('demoLoginBtn').onclick=loginDemo;$('logoutBtn').onclick=logout;$('findBtn').onclick=findParticipant;$('participantNo').onkeydown=e=>{if(e.key==='Enter')findParticipant()};$('programFilter').onchange=renderDashboard;$('historyRefresh').onclick=renderHistory;$('exportBtn').onclick=exportCSV;$('clearLocalBtn').onclick=()=>{if(confirm('Hapus seluruh data penilaian lokal?')){saveAll([]);renderDashboard();renderHistory();renderStatus();toast('Data lokal dihapus.')}};$('syncBtn').onclick=$('adminSyncBtn').onclick=()=>toast(cloudReady()?'Cloud akan diaktifkan pada tahap berikutnya.':'Database online belum dihubungkan.');$('seedBtn').onclick=()=>toast('Database online belum dihubungkan.');document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));window.addEventListener('online',()=>{ $('onlineBadge').textContent='Online';$('onlineBadge').classList.add('online')});window.addEventListener('offline',()=>{$('onlineBadge').textContent='Offline';$('onlineBadge').classList.remove('online')});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=()=>{if(state.deferredInstall)state.deferredInstall.prompt()};if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});try{state.user=JSON.parse(localStorage.getItem('mpkpmb29_user')||'null')}catch{};if(state.user)enterApp()}
document.addEventListener('DOMContentLoaded',init);
})();