(()=>{'use strict';
const USER_KEY='mpkpmb29_user';
const DB_NAME='mpkpmb29_photo_queue',STORE='pending',DB_VERSION=1;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]||c));
let enhancing=false;
function user(){try{return JSON.parse(localStorage.getItem(USER_KEY)||'null')}catch{return null}}
function toast(msg){const e=$('toast');if(!e)return alert(msg);e.textContent=msg;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),3300)}
function cloud(){return window.MPK_CLOUD||null}
function participant(){const n=parseInt($('participantNo')?.value||'',10);return (window.MPK_ROSTER||[]).find(x=>x.id===n)||null}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'participant_id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function pendingGet(id){const d=await openDb();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(Number(id));r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function pendingPut(v){const d=await openDb();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function pendingDelete(id){const d=await openDb();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(Number(id));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function pendingAll(){const d=await openDb();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function readAsDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
function loadImage(url){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url})}
async function compress(file){const src=await readAsDataUrl(file),img=await loadImage(src);const maxW=600,maxH=800,scale=Math.min(1,maxW/img.width,maxH/img.height);const w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);let quality=.78,data=canvas.toDataURL('image/jpeg',quality);while(data.length>900000&&quality>.48){quality-=.08;data=canvas.toDataURL('image/jpeg',quality)}return{dataUrl:data,mime:'image/jpeg',width:w,height:h}}
function injectCss(){if(document.getElementById('photoFeatureCss'))return;const s=document.createElement('style');s.id='photoFeatureCss';s.textContent=`.participant-photo-panel{display:grid;grid-template-columns:92px 1fr;gap:12px;align-items:start;margin-top:12px;padding-top:12px;border-top:1px solid #dfe7ef}.participant-photo-frame{width:92px;height:116px;border-radius:14px;overflow:hidden;background:#edf3f2;border:1px solid #d4e1df;display:grid;place-items:center;position:relative}.participant-photo-frame img{width:100%;height:100%;object-fit:cover;display:block}.participant-photo-placeholder{font-size:34px;color:#8aa6a2}.participant-photo-info{min-width:0}.participant-photo-title{font-weight:900;color:#0b5d56;margin-bottom:3px}.participant-photo-status{font-size:11px;line-height:1.35;color:#64748b;margin-bottom:9px}.photo-actions{display:flex;flex-wrap:wrap;gap:7px}.photo-action{border:1px solid #c8dcda;background:#fff;color:#0b5d56;border-radius:10px;padding:8px 9px;font-weight:800;font-size:12px;cursor:pointer}.photo-action.primary-photo{background:#0b5d56;color:#fff;border-color:#0b5d56}.photo-pending-badge{display:inline-block;background:#fff4d8;color:#8b5e00;border:1px solid #edd598;border-radius:999px;padding:3px 7px;font-size:10px;font-weight:800;margin-top:5px}@media(max-width:390px){.participant-photo-panel{grid-template-columns:82px 1fr}.participant-photo-frame{width:82px;height:104px}.photo-action{padding:8px 7px;font-size:11px}}`;document.head.appendChild(s)}
function panelHtml(p){return `<div class="participant-photo-panel" data-photo-panel="${p.id}"><div class="participant-photo-frame"><div class="participant-photo-placeholder">👤</div><img id="participantPhotoImg" alt="Foto ${esc(p.name)}" hidden></div><div class="participant-photo-info"><div class="participant-photo-title">Foto Taruna/i</div><div id="participantPhotoStatus" class="participant-photo-status">Memeriksa foto...</div><div id="photoActions" class="photo-actions"><button type="button" id="takePhotoBtn" class="photo-action primary-photo">📷 Kamera</button><button type="button" id="galleryPhotoBtn" class="photo-action">🖼 Galeri</button></div><input id="photoCameraInput" type="file" accept="image/*" capture="environment" hidden><input id="photoGalleryInput" type="file" accept="image/*" hidden></div></div>`}
function showPhoto(url,status,pending=false){const img=$('participantPhotoImg'),ph=document.querySelector('.participant-photo-placeholder'),st=$('participantPhotoStatus');if(img&&url){img.src=url;img.hidden=false;if(ph)ph.style.display='none'}else if(img){img.hidden=true;if(ph)ph.style.display='grid'}if(st)st.innerHTML=`${esc(status)}${pending?'<br><span class="photo-pending-badge">Menunggu sinkronisasi</span>':''}`}
function setActions(hasCloudPhoto){const a=$('photoActions'),u=user();if(!a)return;const coordinator=u?.role==='coordinator';if(hasCloudPhoto&&!coordinator){a.innerHTML='<span style="font-size:11px;color:#64748b">Foto sudah tersimpan. Penggantian hanya oleh Koordinator.</span>';return}const take=$('takePhotoBtn'),gal=$('galleryPhotoBtn');if(take)take.textContent=hasCloudPhoto?'📷 Ganti Foto':'📷 Kamera';if(gal)gal.textContent=hasCloudPhoto?'🖼 Ganti dari Galeri':'🖼 Galeri'}
async function loadCurrentPhoto(p){let pend=null;try{pend=await pendingGet(p.id)}catch{}if(pend){showPhoto(pend.dataUrl,'Foto sudah diambil di HP.',true);setActions(false)}if(!navigator.onLine){if(!pend)showPhoto(null,'Belum dapat memeriksa foto server karena HP offline.');return}const c=cloud();if(!c?.getPhoto)return;try{const photo=await c.getPhoto(p.id);if(photo?.url){if(!pend)showPhoto(photo.url,`Tersimpan${photo.updated_by?' • oleh '+photo.updated_by:''}`);setActions(true)}else if(!pend){showPhoto(null,'Belum ada foto. Silakan ambil foto atau pilih dari galeri.');setActions(false)}}catch(e){if(!pend)showPhoto(null,e.message||'Foto belum dapat dimuat.')}}
async function handleFile(file,p){if(!file)return;if(!/^image\//.test(file.type||''))return toast('File harus berupa gambar.');try{toast('Memproses foto...');const r=await compress(file);showPhoto(r.dataUrl,'Foto siap disimpan.',!navigator.onLine);const item={participant_id:p.id,dataUrl:r.dataUrl,mime:r.mime,updated_at:new Date().toISOString()};await pendingPut(item);if(navigator.onLine)await uploadPending(item,true);else toast('Foto disimpan di HP. Akan dikirim saat internet tersedia.')}catch(e){toast('Foto gagal diproses: '+(e.message||e))}}
async function uploadPending(item,showMessage=false){const c=cloud();if(!navigator.onLine||!c?.uploadPhoto)return false;try{const photo=await c.uploadPhoto(item.participant_id,item.dataUrl,item.mime);await pendingDelete(item.participant_id);if(participant()?.id===item.participant_id){showPhoto(photo?.url||item.dataUrl,`Foto tersimpan${photo?.updated_by?' • oleh '+photo.updated_by:''}`);setActions(true)}if(showMessage)toast('Foto berhasil disimpan.');return true}catch(e){const msg=String(e?.message||e);if(/Foto sudah ada|Penggantian foto hanya/i.test(msg)){await pendingDelete(item.participant_id);if(participant()?.id===item.participant_id)loadCurrentPhoto(participant())}if(showMessage)toast('Foto belum terkirim: '+msg);return false}}
async function flushPending(){if(!navigator.onLine||!cloud()?.uploadPhoto)return;let rows=[];try{rows=await pendingAll()}catch{return}for(const x of rows)await uploadPending(x,false)}
async function enhance(){if(enhancing)return;const card=$('participantCard'),p=participant();if(!card||!p||card.classList.contains('empty'))return;if(card.querySelector(`[data-photo-panel="${p.id}"]`))return;enhancing=true;try{card.querySelectorAll('[data-photo-panel]').forEach(x=>x.remove());const row=card.querySelector('.row');if(row)row.insertAdjacentHTML('afterend',panelHtml(p));else card.insertAdjacentHTML('afterbegin',panelHtml(p));const ci=$('photoCameraInput'),gi=$('photoGalleryInput'),tb=$('takePhotoBtn'),gb=$('galleryPhotoBtn');if(tb&&ci)tb.onclick=()=>ci.click();if(gb&&gi)gb.onclick=()=>gi.click();if(ci)ci.onchange=()=>{const f=ci.files?.[0];ci.value='';handleFile(f,p)};if(gi)gi.onchange=()=>{const f=gi.files?.[0];gi.value='';handleFile(f,p)};await loadCurrentPhoto(p)}finally{enhancing=false}}
function init(){injectCss();const card=$('participantCard');if(card)new MutationObserver(()=>setTimeout(enhance,0)).observe(card,{childList:true,subtree:true});$('findBtn')?.addEventListener('click',()=>setTimeout(enhance,30));$('participantNo')?.addEventListener('keydown',e=>{if(e.key==='Enter')setTimeout(enhance,30)});window.addEventListener('online',()=>setTimeout(async()=>{await flushPending();enhance()},900));window.addEventListener('mpk-cloud-ready',()=>{flushPending();enhance()});setTimeout(()=>{flushPending();enhance()},1200);setInterval(flushPending,45000);window.MPK_PHOTO={enhance,flushPending}}
document.addEventListener('DOMContentLoaded',init);
})();