window.MPK_ROSTER = [
  {"id":1,"code":"01","name":"ABDIL GIAN ABYACTA","program":"TPI"},
  {"id":2,"code":"02","name":"ADITIA PRATAMA NGIU","program":"TPI"},
  {"id":3,"code":"03","name":"AFLAH MURSIDI","program":"TPI"},
  {"id":4,"code":"04","name":"AHMAD RAUSHAN FIKRI","program":"TPI"},
  {"id":5,"code":"05","name":"ALKIFRIN LADINA","program":"TPI"},
  {"id":6,"code":"06","name":"ASHARI POTABUGA","program":"TPI"},
  {"id":7,"code":"07","name":"DANIEL","program":"TPI"},
  {"id":8,"code":"08","name":"DOMINGGUS","program":"TPI"},
  {"id":9,"code":"09","name":"ERTON NDAWA MARAMBA AMAH","program":"TPI"},
  {"id":10,"code":"10","name":"ERVANDY RIFAEL PADATI","program":"TPI"},
  {"id":11,"code":"11","name":"FAHRIL CAHYO ALAQBAR SYAWAL","program":"TPI"},
  {"id":12,"code":"12","name":"FARHAN","program":"TPI"},
  {"id":13,"code":"13","name":"FERNANDO ANUGRAH MOONIK","program":"TPI"},
  {"id":14,"code":"14","name":"FRANSISCO SEBASTIANUS AMASANAN","program":"TPI"},
  {"id":15,"code":"15","name":"GIVEN ERLANGGA KAPELE","program":"TPI"},
  {"id":16,"code":"16","name":"GIVENLY ZEFANYA ANTOW","program":"TPI"},
  {"id":17,"code":"17","name":"HOSEA ARGHA PANDAA","program":"TPI"},
  {"id":18,"code":"18","name":"JAIDEN FAREL MANANSANG","program":"TPI"},
  {"id":19,"code":"19","name":"JULYANDRA PUTRA K. UMAR","program":"TPI"},
  {"id":20,"code":"20","name":"LEONARDO GABRIEL TURAMBI","program":"TPI"},
  {"id":21,"code":"21","name":"MUH FADJRIN","program":"TPI"},
  {"id":22,"code":"22","name":"MUH FAHRI","program":"TPI"},
  {"id":23,"code":"23","name":"MUHHAMAD FADLI AINIL ABIDIN","program":"TPI"},
  {"id":24,"code":"24","name":"REFENLI ADRIANTO ANDOLO","program":"TPI"},
  {"id":25,"code":"25","name":"RENDI PATANGATA","program":"TPI"},
  {"id":26,"code":"26","name":"RIKO RATU","program":"TPI"},
  {"id":27,"code":"27","name":"SCHWARZ LESAWENGAN","program":"TPI"},
  {"id":28,"code":"28","name":"SEMI UMBU YIWA RATUMBANI","program":"TPI"},
  {"id":29,"code":"29","name":"TINO ISTIQFACHRI BUDYAWAN","program":"TPI"},
  {"id":30,"code":"30","name":"VIKKY YORDAN PELLAE","program":"TPI"},
  {"id":31,"code":"31","name":"ABDUL ROHMAN HAMID","program":"MP"},
  {"id":32,"code":"32","name":"AHMAD RAIHAN PAPUTUNGAN","program":"MP"},
  {"id":33,"code":"33","name":"AINUL YAQIN","program":"MP"},
  {"id":34,"code":"34","name":"ALDI","program":"MP"},
  {"id":35,"code":"35","name":"ALVARO PAWAN","program":"MP"},
  {"id":36,"code":"36","name":"ANDI MUH. WAHYU SESAR SAPUTRA","program":"MP"},
  {"id":37,"code":"37","name":"APNER","program":"MP"},
  {"id":38,"code":"38","name":"ARTHUR MARDRIAN KANDAI","program":"MP"},
  {"id":39,"code":"39","name":"CHRISTHIO DECO MANGARONDA","program":"MP"},
  {"id":40,"code":"40","name":"DAVA","program":"MP"},
  {"id":41,"code":"41","name":"DESWARDI MARANATHA","program":"MP"},
  {"id":42,"code":"42","name":"DIMAS PERMANA","program":"MP"},
  {"id":43,"code":"43","name":"FREEJEN LEVI PUSUNG","program":"MP"},
  {"id":44,"code":"44","name":"IGNASIUS OLIVER STENLY","program":"MP"},
  {"id":45,"code":"45","name":"JOHN PAUL MAULANA","program":"MP"},
  {"id":46,"code":"46","name":"JOLAD LUKAS SAWEDULING LINDO","program":"MP"},
  {"id":47,"code":"47","name":"MANTO YABU PURU HONGGA","program":"MP"},
  {"id":48,"code":"48","name":"MAYGLAN CRISTIAN TINUNDIGHANG","program":"MP"},
  {"id":49,"code":"49","name":"MUH. TIRTA ATHALLAH","program":"MP"},
  {"id":50,"code":"50","name":"MUHAMMAD NUR RIZKY ABDULLAH","program":"MP"},
  {"id":51,"code":"51","name":"RASUL HIDAYAT","program":"MP"},
  {"id":52,"code":"52","name":"REFANDI LAMADA","program":"MP"},
  {"id":53,"code":"53","name":"REVANDI MBAKU NJUKA ANDUNG","program":"MP"},
  {"id":54,"code":"54","name":"REYHAN ONTONG","program":"MP"},
  {"id":55,"code":"55","name":"RIANDI MARTIN ANTOU","program":"MP"},
  {"id":56,"code":"56","name":"ABRIANY BEHTLANY","program":"TPPP"},
  {"id":57,"code":"57","name":"AISYAH NUR HASAN","program":"TPPP"},
  {"id":58,"code":"58","name":"ANDIKA PRATAMA","program":"TPPP"},
  {"id":59,"code":"59","name":"ANUGRAH MAR'ATUSAHILAH","program":"TPPP"},
  {"id":60,"code":"60","name":"ARY IHSAN KURNIAWAN","program":"TPPP"},
  {"id":61,"code":"61","name":"DEBORA MANGALEHE","program":"TPPP"},
  {"id":62,"code":"62","name":"FANY ANUGERAH","program":"TPPP"},
  {"id":63,"code":"63","name":"FIKA FADILLAH AD HARU","program":"TPPP"},
  {"id":64,"code":"64","name":"FRANWINSTALIN PM","program":"TPPP"},
  {"id":65,"code":"65","name":"GITA DWIYANTI ALTING","program":"TPPP"},
  {"id":66,"code":"66","name":"JUAN RAFEL TAMO","program":"TPPP"},
  {"id":67,"code":"67","name":"KATHARINA ALVIANI WEA KUA","program":"TPPP"},
  {"id":68,"code":"68","name":"MEILAN TIROLETU","program":"TPPP"},
  {"id":69,"code":"69","name":"MUHAMMAD ARYA SAPUTRA","program":"TPPP"},
  {"id":70,"code":"70","name":"MUHAMMAD FATIR","program":"TPPP"},
  {"id":71,"code":"71","name":"MUHAMMAD IRFAN DWI CAHYO","program":"TPPP"},
  {"id":72,"code":"72","name":"NUR RAHMI ZALZABILA","program":"TPPP"},
  {"id":73,"code":"73","name":"OCTAVIOLA KOHO","program":"TPPP"},
  {"id":74,"code":"74","name":"PANDI R. ABDULLAH","program":"TPPP"},
  {"id":75,"code":"75","name":"PURISKA","program":"TPPP"},
  {"id":76,"code":"76","name":"RAHMAWATI HAMADI","program":"TPPP"},
  {"id":77,"code":"77","name":"SITI HAFSYAH","program":"TPPP"},
  {"id":78,"code":"78","name":"SITI SARIA","program":"TPPP"},
  {"id":79,"code":"79","name":"STEFAN JEFANDRI MAMELAS","program":"TPPP"},
  {"id":80,"code":"80","name":"SYARIF","program":"TPPP"}
];
