const API='https://fplimalvdaedvxrzwqgl.supabase.co/functions/v1/mpk-coordinator-planner';
const state={pin:'',member:null,date:'',home:null,programs:[],month:'Semua'};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STATUS={planned:'Direncanakan',scheduled:'Dijadwalkan',in_progress:'Berlangsung',done:'Selesai',postponed:'Ditunda',cancelled:'Dibatalkan'};
const MONTHS=['Semua','Agustus','September','Oktober','November','Desember'];

function toast(m,e=false){const t=$('toast');t.textContent=m;t.className='toast show'+(e?' err':'');clearTimeout(toast.tm);toast.tm=setTimeout(()=>t.className='toast',3300)}
function witaParts(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()),o={};p.forEach(x=>o[x.type]=x.value);return {date:`${o.year}-${o.month}-${o.day}`,time:`${o.hour}:${o.minute}`}}
function fmtDate(s){if(!s)return'-';try{return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s+'T12:00:00+08:00'))}catch{return s}}
function fmtRange(p){return p.scheduled_date?`${fmtDate(p.scheduled_date)}${p.scheduled_time?' • '+String(p.scheduled_time).slice(0,5)+' WITA':''}`:`${fmtDate(p.start_date)} – ${fmtDate(p.end_date)}`}
function mins(t){const[a,b]=String(t||'00:00').split(':').map(Number);return a*60+b}
function statusClass(s){return s==='done'?'good':s==='in_progress'?'run':s==='postponed'||s==='cancelled'?'bad':s==='scheduled'?'blue':'warn'}
function setBusy(btn,on,text){if(!btn)return;if(on){btn.dataset.old=btn.textContent;btn.disabled=true;btn.textContent=text}else{btn.disabled=false;btn.textContent=btn.dataset.old||text}}

async function api(action,p={}){let r;try{r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...p,...(state.pin?{pin:state.pin}:{})})})}catch{throw new Error('Tidak dapat terhubung ke server Planner Koordinator.')}let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||`Server ${r.status}`);return d}

async function login(){const pin=$('loginPin').value.trim();if(!/^\d{6,12}$/.test(pin))return toast('PIN harus 6–12 angka.',true);const b=$('loginBtn');setBusy(b,true,'Masuk...');try{state.pin=pin;const d=await api('login');state.member=d.member;state.date=d.server?.date||witaParts().date;$('dateInput').value=state.date;$('userName').textContent=d.member.display_name||'Koordinator';$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await Promise.all([loadHome(),loadPrograms()]);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});startClock()}catch(e){state.pin='';toast(e.message,true)}finally{setBusy(b,false,'MASUK')}}
function logout(){state.pin='';state.member=null;state.home=null;state.programs=[];$('loginPin').value='';$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}

async function loadHome(){try{state.home=await api('home',{date:state.date});renderHome();renderDaily();renderTasks()}catch(e){toast(e.message,true)}}
async function loadPrograms(){try{const d=await api('programs');state.programs=d.programs||[];renderProgramFilters();renderPrograms();renderSpecial()}catch(e){toast(e.message,true)}}

function startClock(){clearInterval(startClock.tm);const tick=()=>{const p=witaParts();$('clock').textContent=p.time+' WITA';if(state.date===p.date&&state.home)renderNow()};tick();startClock.tm=setInterval(tick,30000)}
function renderNow(){const h=state.home,p=witaParts();if(!h)return;if(state.date!==p.date){$('nowActivity').textContent='Jadwal tanggal dipilih';$('nextActivity').textContent='Lihat urutan kegiatan di bawah';return}const n=mins(p.time),arr=h.daily_schedule||[];let current=null,next=null;for(let i=0;i<arr.length;i++){const s=mins(arr[i].start),e=mins(arr[i].end);const overnight=e<=s;if((!overnight&&n>=s&&n<e)||(overnight&&(n>=s||n<e))){current=arr[i];next=arr[(i+1)%arr.length];break}if(!overnight&&n<s&&!next)next=arr[i]}$('nowActivity').textContent=current?current.title:'Di luar rentang kegiatan';$('nextActivity').textContent=next?`Berikutnya ${next.start} • ${next.title}`:'—'}

function renderHome(){const h=state.home;if(!h)return;$('todayEyebrow').textContent=`${h.day.day.toUpperCase()} • FOKUS HARI INI`;$('todayFocus').textContent=h.day.focus;$('todayTarget').textContent=`Sasaran: ${h.day.target}. Program malam: ${h.day.night}.`;renderNow();const logs=new Map((h.action_logs||[]).map(x=>[x.action_key,x])),done=(h.actions||[]).filter(a=>logs.get(a.key)?.status==='done').length,active=(h.active_programs||[]).length,confirm=(h.active_programs||[]).filter(x=>x.date_needs_confirmation&&!x.scheduled_date).length,custom=(h.custom_tasks||[]).filter(x=>x.status==='pending').length;$('todayMetrics').innerHTML=[[`${done}/${(h.actions||[]).length}`,'Checklist selesai'],[active,'Program aktif'],[confirm,'Tanggal perlu ditetapkan'],[custom,'Tugas tambahan']].map(x=>`<div class="metric"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');renderActions();renderActivePrograms()}

function renderActions(){const h=state.home,logs=new Map((h.action_logs||[]).map(x=>[x.action_key,x]));const arr=h.actions||[];$('actionList').innerHTML=arr.length?arr.map(a=>{const l=logs.get(a.key),done=l?.status==='done',sk=l?.status==='skipped';return `<div class="action ${done?'done':''}"><button class="check ${done?'checked':''}" onclick="toggleAction('${esc(a.key)}','${done?'pending':'done'}')">${done?'✓':''}</button><div><b>${a.time?esc(a.time)+' • ':''}${esc(a.title)}</b><small>${a.type==='program'?'Program terencana':a.type==='perencanaan'?'Perlu keputusan Koordinator':a.type==='evaluasi'?'Evaluasi berkala':'Tugas Koordinator'}${l?.note?' • '+esc(l.note):''}</small></div><button class="more" onclick="openActionNote('${esc(a.key)}')">•••</button></div>`}).join(''):'<div class="empty">Tidak ada checklist.</div>'}
async function toggleAction(key,status){try{await api('save_action',{date:state.date,action_key:key,status});await loadHome()}catch(e){toast(e.message,true)}}
function openActionNote(key){const l=(state.home.action_logs||[]).find(x=>x.action_key===key);$('modalTitle').textContent='Catatan Checklist';$('modalMeta').textContent=state.date;$('modalBody').innerHTML=`<label class="label">Catatan</label><textarea id="actionNote" placeholder="Catatan singkat…">${esc(l?.note||'')}</textarea><button class="btn primary full" onclick="saveActionNote('${esc(key)}')">Simpan Catatan</button>`;openModal()}
async function saveActionNote(key){try{const old=(state.home.action_logs||[]).find(x=>x.action_key===key);await api('save_action',{date:state.date,action_key:key,status:old?.status||'pending',note:$('actionNote').value});closeModal();await loadHome();toast('Catatan disimpan.')}catch(e){toast(e.message,true)}}

function programCard(p,compact=false){const need=p.date_needs_confirmation&&!p.scheduled_date;return `<div class="program-card ${need?'needs-date':''}"><div class="program-top"><div><span class="pill">${esc(p.period_label)}</span>${need?'<span class="pill alert">Tanggal belum ditetapkan</span>':''}<h4>${esc(p.focus)}</h4></div><span class="status ${statusClass(p.status)}">${STATUS[p.status]||p.status}</span></div><div class="program-date">${esc(fmtRange(p))}${p.location?' • '+esc(p.location):''}</div>${compact?'':`<p>${esc(p.activities)}</p><small><b>Target:</b> ${esc(p.target||'-')}<br><b>PIC:</b> ${esc(p.pic||'-')}</small>`}<button class="btn small" onclick="openProgram(${p.id})">Buka / Atur</button></div>`}
function renderActivePrograms(){const a=state.home.active_programs||[],n=(state.home.next_programs||[]).filter(x=>!a.some(y=>y.id===x.id)).slice(0,3);$('activePrograms').innerHTML=a.length?a.map(p=>programCard(p,true)).join(''):'<div class="empty">Tidak ada paket program aktif pada tanggal ini.</div>';$('nextPrograms').innerHTML=n.length?n.map(p=>programCard(p,true)).join(''):'<div class="empty">Tidak ada program berikutnya.</div>'}

function renderDaily(){const h=state.home;if(!h)return;$('dailySubtitle').textContent=`${h.day.day} • fokus sore: ${h.day.focus} • program malam: ${h.day.night}`;const p=witaParts(),today=state.date===p.date,n=today?mins(p.time):-1;$('dailyTimeline').innerHTML=(h.daily_schedule||[]).map((x,i)=>{const s=mins(x.start),e=mins(x.end),overnight=e<=s,current=today&&((!overnight&&n>=s&&n<e)||(overnight&&(n>=s||n<e)));return `<div class="time-row ${current?'current':''}"><div class="time"><b>${esc(x.start)}</b><span>${esc(x.end)}</span></div><div class="dot"></div><div><b>${esc(x.title)}</b><small>${esc(x.place)} • ${esc(x.kind)}</small></div></div>`}).join('')}

function renderProgramFilters(){$('monthFilter').innerHTML=MONTHS.map(m=>`<button class="filter ${state.month===m?'active':''}" onclick="setMonth('${m}')">${m}</button>`).join('')}
function setMonth(m){state.month=m;renderProgramFilters();renderPrograms()}
function renderPrograms(){const rows=state.month==='Semua'?state.programs:state.programs.filter(x=>x.month_name===state.month);$('programList').innerHTML=rows.length?rows.map(p=>programCard(p)).join(''):'<div class="empty">Tidak ada program.</div>'}
function renderSpecial(){const rows=state.programs.filter(p=>p.period_label==='Program Khusus'||p.period_label==='Evaluasi Bulanan'||p.period_label==='Akhir Program'||p.date_needs_confirmation);$('specialList').innerHTML=rows.length?rows.map(p=>programCard(p)).join(''):'<div class="empty">Tidak ada kegiatan khusus.</div>'}
function openProgram(id){const p=state.programs.find(x=>Number(x.id)===Number(id))||state.home?.active_programs?.find(x=>Number(x.id)===Number(id));if(!p)return;$('modalTitle').textContent=p.focus;$('modalMeta').textContent=`${p.month_name} • ${p.period_label} • ${fmtDate(p.start_date)}–${fmtDate(p.end_date)}`;$('modalBody').innerHTML=`<div class="detail"><p>${esc(p.activities)}</p><small><b>Target:</b> ${esc(p.target||'-')}<br><b>PIC:</b> ${esc(p.pic||'-')}</small></div><label class="label">Tanggal pelaksanaan spesifik</label><input id="progDate" class="control" type="date" value="${esc(p.scheduled_date||'')}"><label class="label">Jam</label><input id="progTime" class="control" type="time" value="${esc(p.scheduled_time?String(p.scheduled_time).slice(0,5):'')}"><label class="label">Tempat</label><input id="progLocation" class="control" value="${esc(p.location||'')}"><label class="label">Status</label><select id="progStatus" class="control">${Object.entries(STATUS).map(([v,l])=>`<option value="${v}" ${p.status===v?'selected':''}>${l}</option>`).join('')}</select><label class="label">Catatan Koordinator</label><textarea id="progNotes">${esc(p.notes||'')}</textarea><button class="btn primary full" onclick="saveProgram(${p.id})">Simpan Perubahan</button>`;openModal()}
async function saveProgram(id){try{await api('update_program',{id,scheduled_date:$('progDate').value,scheduled_time:$('progTime').value,location:$('progLocation').value,status:$('progStatus').value,notes:$('progNotes').value});closeModal();await Promise.all([loadPrograms(),loadHome()]);toast('Program diperbarui.')}catch(e){toast(e.message,true)}}

function renderTasks(){const rows=state.home?.custom_tasks||[];$('customTaskList').innerHTML=rows.length?rows.map(t=>`<div class="action ${t.status==='done'?'done':''}"><button class="check ${t.status==='done'?'checked':''}" onclick="setTaskStatus('${t.id}','${t.status==='done'?'pending':'done'}')">${t.status==='done'?'✓':''}</button><div><b>${t.time_start?String(t.time_start).slice(0,5)+' • ':''}${esc(t.title)}</b><small>${t.priority==='important'?'Penting':'Normal'}${t.note?' • '+esc(t.note):''}</small></div><button class="more" onclick="deleteTask('${t.id}')">×</button></div>`).join(''):'<div class="empty">Belum ada tugas tambahan pada tanggal ini.</div>'}
function openTaskForm(){$('modalTitle').textContent='Tambah Tugas Saya';$('modalMeta').textContent=fmtDate(state.date);$('modalBody').innerHTML=`<label class="label">Tanggal</label><input id="taskDate" class="control" type="date" value="${state.date}"><label class="label">Jam</label><input id="taskTime" class="control" type="time"><label class="label">Tugas</label><input id="taskTitle" class="control" placeholder="Contoh: Hubungi narasumber Seminar 1"><label class="label">Prioritas</label><select id="taskPriority" class="control"><option value="normal">Normal</option><option value="important">Penting</option></select><label class="label">Catatan</label><textarea id="taskNote"></textarea><button class="btn primary full" onclick="saveTask()">Tambah Tugas</button>`;openModal()}
async function saveTask(){try{await api('add_task',{task_date:$('taskDate').value,time_start:$('taskTime').value,title:$('taskTitle').value,priority:$('taskPriority').value,note:$('taskNote').value});closeModal();if($('taskDate').value===state.date)await loadHome();toast('Tugas ditambahkan.')}catch(e){toast(e.message,true)}}
async function setTaskStatus(id,status){try{await api('update_task',{id,status});await loadHome()}catch(e){toast(e.message,true)}}
async function deleteTask(id){if(!confirm('Hapus tugas ini?'))return;try{await api('delete_task',{id});await loadHome();toast('Tugas dihapus.')}catch(e){toast(e.message,true)}}

async function changePin(){const a=$('newPin1').value.trim(),b=$('newPin2').value.trim();if(!/^\d{6,12}$/.test(a))return toast('PIN baru harus 6–12 angka.',true);if(a!==b)return toast('Pengulangan PIN tidak sama.',true);try{await api('change_pin',{new_pin:a});state.pin=a;$('newPin1').value='';$('newPin2').value='';toast('PIN berhasil diganti.')}catch(e){toast(e.message,true)}}

function showTab(t){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));document.querySelectorAll('.tabview').forEach(x=>x.classList.toggle('hidden',x.id!==`tab-${t}`))}
function openModal(){$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}

document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('loginBtn').onclick=login;$('loginPin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
$('logoutBtn').onclick=logout;$('refreshBtn').onclick=async()=>{await Promise.all([loadHome(),loadPrograms()]);toast('Jadwal diperbarui.')};
$('todayBtn').onclick=async()=>{state.date=witaParts().date;$('dateInput').value=state.date;await loadHome()};
$('dateInput').onchange=async e=>{state.date=e.target.value;await loadHome()};
$('addTaskBtn').onclick=openTaskForm;$('addTaskTop').onclick=openTaskForm;$('changePinBtn').onclick=changePin;
$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};
