const EXEC_API='https://fplimalvdaedvxrzwqgl.supabase.co/functions/v1/mpk-executive';
const COMPANION_API='https://fplimalvdaedvxrzwqgl.supabase.co/functions/v1/mpk-companion';
const INCIDENTAL_API='https://fplimalvdaedvxrzwqgl.supabase.co/functions/v1/mpk-incidental';
const SPIRITUAL_API='https://fplimalvdaedvxrzwqgl.supabase.co/functions/v1/mpk-spiritual';

const GROUPS=[
 {start:1,end:12,supervisor:'Fahriadi'},
 {start:13,end:24,supervisor:'Gerald'},
 {start:25,end:36,supervisor:'Andi Wiguna'},
 {start:37,end:48,supervisor:'Samsul'},
 {start:49,end:60,supervisor:'Kholid'},
 {start:61,end:72,supervisor:'Iki'},
 {start:73,end:80,supervisor:'Alexander Tumewu'}
];
const DAYS=['','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'];
const TRAINING_PLAN=[
 {month:'Agustus',topic:'Identitas Pendamping & Juklak',detail:'Filosofi MPK-PMB, tugas, batas kewenangan, keteladanan, antikekerasan dan alur pelaporan.'},
 {month:'September',topic:'Komunikasi & Disiplin Positif',detail:'Memberi instruksi, teguran yang tepat, observasi perilaku, pencatatan fakta dan debrief singkat.'},
 {month:'Oktober',topic:'Coaching & Pengembangan Potensi',detail:'Motivasi, mentoring, minat-bakat, komunikasi kelompok dan penguatan kemampuan peserta.'},
 {month:'November',topic:'Kepemimpinan & Problem Solving',detail:'Manajemen konflik, pengambilan keputusan, peer learning dan pembinaan kemandirian.'},
 {month:'Desember',topic:'Evaluasi & Umpan Balik',detail:'Teknik evaluasi, refleksi, rekomendasi pembinaan lanjutan dan penutupan tugas pendamping.'}
];
const LS_COACH='mpk_coord_coaching_v1';
const LS_SPECIAL='mpk_coord_special_seniors_v1';

const state={
 coordName:'',pin:'',member:null,date:'',exec:null,monitor:null,groupHomes:new Map(),participants:[],incidental:[],spiritualNames:[],specialNames:{spiritual:['',''],bk:['','']},coaching:[]
};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
function witaDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function fmtDate(s){try{return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(s+'T12:00:00+08:00'))}catch{return s}}
function toast(m,e=false){const t=$('toast');t.textContent=m;t.className='toast show'+(e?' err':'');clearTimeout(toast.tm);toast.tm=setTimeout(()=>t.className='toast',3400)}
function setBusy(btn,on,label){if(!btn)return;if(on){btn.dataset.old=btn.textContent;btn.disabled=true;btn.textContent=label}else{btn.disabled=false;btn.textContent=btn.dataset.old||label}}
async function post(url,body){let r;try{r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}catch{throw new Error('Tidak dapat terhubung ke server. Periksa koneksi internet.')}let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||`Server ${r.status}`);return d}
async function execApi(action,p={}){return post(EXEC_API,{action,...p,...(state.coordName&&!['list_members','login'].includes(action)?{name:state.coordName,pin:state.pin}:{})})}
async function companionApi(action,p={}){return post(COMPANION_API,{action,...p,...(state.coordName&&!['list_members','login'].includes(action)?{name:state.coordName}:{})})}
async function incidentalApi(action,p={}){return post(INCIDENTAL_API,{action,...p,name:state.coordName})}
async function spiritualApi(group,action,p={}){return post(SPIRITUAL_API,{action,...p,worship_group:group,...(state.coordName&&!['list_members','login'].includes(action)?{name:state.coordName}:{})})}

function loadLocal(){try{state.coaching=JSON.parse(localStorage.getItem(LS_COACH)||'[]')}catch{state.coaching=[]}try{const x=JSON.parse(localStorage.getItem(LS_SPECIAL)||'{}');if(Array.isArray(x.spiritual))state.specialNames.spiritual=x.spiritual;if(Array.isArray(x.bk))state.specialNames.bk=x.bk}catch{}}
function saveLocal(){localStorage.setItem(LS_COACH,JSON.stringify(state.coaching));localStorage.setItem(LS_SPECIAL,JSON.stringify(state.specialNames))}

async function init(){loadLocal();state.date=witaDate();$('dateInput').value=state.date;try{const d=await execApi('list_members');const members=d.members||[];const c=members.find(x=>x.role==='coordinator')||members.find(x=>/fahriadi/i.test(x.display_name||''));if(!c)throw new Error('Akun Koordinator belum ditemukan pada server Monitoring Pimpinan.');state.coordName=c.display_name;$('coordIdentity').textContent=c.display_name+' — Koordinator MPK-PMB'}catch(e){$('coordIdentity').textContent='Koordinator MPK-PMB';toast(e.message,true)}}

async function login(){const pin=$('loginPin').value.trim();if(!state.coordName)return toast('Akun Koordinator belum berhasil dimuat.',true);if(!/^\d{6,12}$/.test(pin))return toast('PIN harus 6–12 angka.',true);const b=$('loginBtn');setBusy(b,true,'Memverifikasi...');try{const d=await execApi('login',{name:state.coordName,pin});if(d.member?.role&&d.member.role!=='coordinator')throw new Error('Akun ini bukan akun Koordinator.');state.pin=pin;state.member=d.member;$('userName').textContent=state.coordName;$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await loadAll();if(d.member?.must_change_pin)showTab('security')}catch(e){toast(e.message,true)}finally{setBusy(b,false,'MASUK CONTROL CENTER')}}
function logout(){state.pin='';state.member=null;state.exec=null;state.monitor=null;state.groupHomes.clear();$('loginPin').value='';$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}

async function loadAll(){const b=$('refreshBtn');setBusy(b,true,'…');$('onlineBadge').textContent='● Memuat';try{state.date=$('dateInput').value||witaDate();const tasks=[execApi('dashboard',{date:state.date}),companionApi('monitor',{date:state.date}),incidentalApi('list')];const [ex,mon,inc]=await Promise.all(tasks);state.exec=ex;state.monitor=mon;state.incidental=inc.activities||[];const homes=await Promise.all(GROUPS.map(g=>companionApi('home',{date:state.date,assignment_start:g.start}).catch(()=>null)));state.groupHomes.clear();homes.forEach((h,i)=>{if(h)state.groupHomes.set(GROUPS[i].start,h)});const pm=new Map();for(const h of state.groupHomes.values())for(const p of h.participants||[])pm.set(Number(p.id),p);state.participants=[...pm.values()].sort((a,b)=>Number(a.id)-Number(b.id));await loadSpiritualNames();renderAll();$('onlineBadge').textContent='● Online';$('onlineBadge').style.color='var(--good)'}catch(e){$('onlineBadge').textContent='● Gangguan';$('onlineBadge').style.color='var(--bad)';toast(e.message,true)}finally{setBusy(b,false,'↻')}}
async function loadSpiritualNames(){const names=[];for(const grp of ['islam','christian_catholic']){try{const d=await spiritualApi(grp,'list_members');for(const m of d.members||[]){if(m.full_access)continue;if(m.display_name&&!names.includes(m.display_name))names.push(m.display_name)}}catch{}}state.spiritualNames=names.slice(0,2);if(state.spiritualNames.length){state.specialNames.spiritual=[state.spiritualNames[0]||'',state.spiritualNames[1]||''];saveLocal()}}

function renderAll(){renderDashboard();renderGroups();renderCatar();renderSeniors();renderCoaching();renderAgenda();renderAssessment();renderIssues();renderReport()}
function overallLabel(p){if(p>=90)return['Pelaksanaan berjalan baik','Kegiatan rutin dan pelaporan mayoritas terkendali.','good'];if(p>=75)return['Pelaksanaan berjalan, ada beberapa perhatian','Prioritaskan kelompok atau kegiatan yang belum tercatat.','warn'];return['Pelaksanaan memerlukan perhatian','Periksa kegiatan, kehadiran dan tindak lanjut yang belum selesai.','bad']}
function renderDashboard(){const e=state.exec||{},s=e.summary||{},a=s.attendance||{},p=Number(s.completion_pct||0),lab=overallLabel(p);$('heroTitle').textContent=lab[0];$('heroText').textContent=lab[1];$('heroPct').textContent=p+'%';$('summaryCards').innerHTML=[
 [p+'%','Pelaksanaan',lab[2]],[a.attendance_pct==null?'—':a.attendance_pct+'%','Kehadiran',a.attendance_pct>=95?'good':a.attendance_pct>=85?'warn':'bad'],[s.not_started||0,'Belum Tercatat',s.not_started?'warn':'good'],[s.issues||0,'Perlu Perhatian',s.issues?'warn':'good']
].map(x=>`<div class="metric ${x[2]}"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');
 const sec=e.sections||{},areas=[['Pendamping',sec.pendamping],['Kerohanian',sec.kerohanian],['Bimbingan & Konseling',sec.bk]];$('areaCards').innerHTML=areas.map(([n,x])=>{x=x||{};let sub='Data belum tersedia';if(n==='Pendamping')sub=`${x.completed||0}/${x.expected||0} kegiatan selesai`;else if(n==='Kerohanian')sub=`${x.completed||0}/${x.expected||0} kegiatan selesai`;else sub=`${x.urgent_observations||0} observasi prioritas`;return `<div class="item"><div class="ico">${n==='Pendamping'?'P':n==='Kerohanian'?'K':'BK'}</div><div><b>${n}</b><small>${sub}</small></div></div>`}).join('');
 $('dashboardIssues').innerHTML=(e.issues||[]).slice(0,5).map(x=>issueHtml(x)).join('')||'<div class="empty">Belum ada isu prioritas dari sistem.</div>';renderGroupCards('dashboardGroups',false);$('groupProgressDate').textContent=fmtDate(state.date)}
function issueHtml(x){return `<div class="item"><div class="ico">!</div><div><b>${esc(x.title||'Perlu perhatian')}</b><small>${esc(x.text||x.description||'')}</small></div><span class="badge warn">Tinjau</span></div>`}

function groupStats(g){const h=state.groupHomes.get(g.start),schedule=(h?.schedule||[]).filter(x=>x.managed_by!=='kerohanian'),logs=h?.logs||[],done=logs.filter(x=>x.status==='completed').length,pct=schedule.length?Math.round(done/schedule.length*100):0;return {h,schedule,logs,done,pct}}
function renderGroupCards(target,buttons=true){$(target).innerHTML=GROUPS.map(g=>{const z=groupStats(g);return `<div class="gcard"><b>${pad(g.start)}–${pad(g.end)} • ${esc(g.supervisor)}</b><div class="progress"><i style="width:${clamp(z.pct,0,100)}%"></i></div><div class="gmeta">${z.done}/${z.schedule.length} kegiatan selesai • ${z.pct}%</div>${buttons?`<button class="btn small" style="margin-top:8px" onclick="openGroup(${g.start})">Buka</button>`:''}</div>`}).join('')}
function renderGroups(){renderGroupCards('groupCards',true)}
function openGroup(start){const g=GROUPS.find(x=>x.start===Number(start)),z=groupStats(g),h=z.h;if(!h)return toast('Data kelompok belum dapat dimuat.',true);$('groupDetailTitle').textContent=`Kelompok ${pad(g.start)}–${pad(g.end)} • ${g.supervisor}`;$('groupDetailMeta').textContent=`${(h.participants||[]).length} Catar-Catir • ${z.done}/${z.schedule.length} kegiatan pendamping selesai`;
 const as=(state.monitor?.assistants||[]).filter(x=>Number(x.assignment_start)===g.start).sort((a,b)=>Number(a.assistant_slot)-Number(b.assistant_slot));$('groupDetail').innerHTML=`<div class="grid-2"><div><b>Pendamping Senior</b>${[1,2].map(i=>{const a=as.find(x=>Number(x.assistant_slot)===i);return `<div class="item" style="margin-top:7px"><div class="ico">T${i}</div><div><b>${esc(a?.display_name||'Belum ditetapkan')}</b><small>Senior Pendamping ${i}</small></div></div>`}).join('')}</div><div><b>Kegiatan Hari Ini</b>${z.schedule.map(s=>{const l=z.logs.find(x=>Number(x.schedule_id)===Number(s.id));return `<div class="item" style="margin-top:7px"><div class="ico">${String(s.time_local||'').slice(0,5)}</div><div><b>${esc(s.activity_name)}</b><small>${l?.status==='completed'?'Selesai':l?.status==='started'?'Berlangsung':'Belum tercatat'}</small></div></div>`}).join('')||'<div class="empty">Tidak ada jadwal.</div>'}</div></div>`}

function groupForParticipant(id){return GROUPS.find(g=>Number(id)>=g.start&&Number(id)<=g.end)}
function renderCatar(){const sel=$('catarGroupFilter');if(!sel.options.length)sel.innerHTML='<option value="all">Semua Kelompok</option>'+GROUPS.map(g=>`<option value="${g.start}">${pad(g.start)}–${pad(g.end)} • ${g.supervisor}</option>`).join('');const q=($('catarSearch').value||'').toLowerCase(),gf=sel.value||'all';let rows=state.participants.filter(p=>`${p.code||''} ${p.name||''} ${p.program||''}`.toLowerCase().includes(q));if(gf!=='all'){const g=GROUPS.find(x=>x.start===Number(gf));rows=rows.filter(p=>Number(p.id)>=g.start&&Number(p.id)<=g.end)}$('catarCount').textContent=`${rows.length} peserta`;$('catarMetrics').innerHTML=[[state.participants.length||80,'Catar-Catir'],[GROUPS.length,'Kelompok'],[(state.exec?.summary?.attendance||{}).late||0,'Terlambat Hari Ini'],[(state.exec?.summary?.attendance||{}).absent||0,'Tidak Hadir']].map(x=>`<div class="metric"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');$('catarList').innerHTML=rows.map(p=>{const g=groupForParticipant(p.id);return `<div class="participant"><div class="num">${esc(p.code||pad(p.id))}</div><div><div class="pname">${esc(p.name)}</div><div class="meta">${esc(p.program||'')} • ${esc(g?.supervisor||'')}</div></div><button class="btn small" onclick="openCatar(${p.id})">Lihat</button></div>`}).join('')||'<div class="empty">Peserta tidak ditemukan.</div>'}
function openCatar(id){const p=state.participants.find(x=>Number(x.id)===Number(id));if(!p)return;const g=groupForParticipant(id),h=state.groupHomes.get(g.start),att=(h?.attendance||[]).filter(a=>Number(a.participant_id)===Number(id));openModal(`${p.code||pad(id)} — ${p.name}`,`${p.program||''} • Kelompok ${pad(g.start)}–${pad(g.end)}`,`<div class="panel" style="box-shadow:none"><p><b>Pendamping Pegawai:</b> ${g.supervisor}</p><p><b>Status hari ini:</b> ${att.length?att.map(a=>esc(a.status)).join(', '):'Belum ada catatan kehadiran yang dapat ditampilkan.'}</p><p class="muted">Control Center menampilkan ringkasan operasional. Detail konseling individual BK tidak ditampilkan di sini.</p></div>`)}

function renderSeniors(){const assistants=state.monitor?.assistants||[],filled=assistants.filter(x=>String(x.display_name||'').trim()).length,sp=state.specialNames.spiritual.filter(Boolean).length,bk=state.specialNames.bk.filter(Boolean).length,total=filled+sp+bk;$('seniorMetrics').innerHTML=[[18,'Total Slot'],[filled,'Pendamping Kelompok'],[sp,'Kerohanian Terisi'],[bk,'BK Terisi']].map(x=>`<div class="metric"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');$('groupSeniorList').innerHTML=GROUPS.flatMap(g=>[1,2].map(i=>{const a=assistants.find(x=>Number(x.assignment_start)===g.start&&Number(x.assistant_slot)===i);return `<div class="senior-card"><div class="role">Kelompok ${pad(g.start)}–${pad(g.end)} • Slot ${i}</div><strong>${esc(a?.display_name||'Belum ditetapkan')}</strong><div class="sub">Pembimbing pegawai: ${esc(g.supervisor)}</div></div>`})).join('');$('spiritualSeniorList').innerHTML=specialList('spiritual','Kerohanian');$('bkSeniorList').innerHTML=specialList('bk','Pendamping BK')}
function specialList(type,label){return [0,1].map(i=>`<div class="item"><div class="ico">${i+1}</div><div><b>${esc(state.specialNames[type][i]||'Belum ditetapkan')}</b><small>${label} ${i+1}</small></div><button class="btn small" onclick="editSpecialSenior('${type}',${i})">Atur</button></div>`).join('')}
function editSpecialSenior(type,i){const old=state.specialNames[type][i]||'';openModal(type==='bk'?'Taruni Senior BK':'Senior Kerohanian',`Slot ${i+1}`,`<label class="label">Nama</label><input id="specialName" class="control" value="${esc(old)}"><button class="btn primary full" onclick="saveSpecialSenior('${type}',${i})">Simpan</button><p class="privacy-note">Nama ini disimpan sebagai konfigurasi pribadi Control Center pada perangkat ini.</p>`)}
function saveSpecialSenior(type,i){state.specialNames[type][i]=String($('specialName').value||'').trim();saveLocal();closeModal();renderSeniors();renderCoaching();toast('Nama senior disimpan.')}
function allSeniorNames(){const a=(state.monitor?.assistants||[]).map(x=>x.display_name).filter(Boolean),s=[...state.specialNames.spiritual,...state.specialNames.bk].filter(Boolean);return [...new Set([...a,...s])]}

function renderCoaching(){const open=state.coaching.filter(x=>x.status!=='done').length,done=state.coaching.filter(x=>x.status==='done').length,people=new Set(state.coaching.map(x=>x.senior).filter(Boolean)).size;$('coachingMetrics').innerHTML=[[state.coaching.length,'Sesi Tercatat'],[open,'Follow-up Terbuka'],[done,'Selesai'],[people,'Senior Terjangkau']].map(x=>`<div class="metric"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');const month=new Intl.DateTimeFormat('id-ID',{month:'long',timeZone:'Asia/Makassar'}).format(new Date());$('trainingPlan').innerHTML=TRAINING_PLAN.map(x=>`<div class="timeline-item ${x.month.toLowerCase()===month.toLowerCase()?'active':''}"><div class="month">${x.month}</div><div><b>${x.topic}</b><small>${x.detail}</small></div></div>`).join('');$('coachingList').innerHTML=state.coaching.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,12).map(x=>`<div class="item"><div class="ico">C</div><div><b>${esc(x.senior||'Senior')}</b><small>${fmtDate(x.date)} • ${esc(x.topic||'Coaching')}<br>${esc(x.direction||x.finding||'')}</small></div><button class="badge ${x.status==='done'?'good':'warn'}" onclick="toggleCoach('${x.id}')">${x.status==='done'?'Selesai':'Terbuka'}</button></div>`).join('')||'<div class="empty">Belum ada coaching yang dicatat pada Control Center.</div>';renderIssues()}
function openCoachingForm(){const opts=allSeniorNames();openModal('Catat Coaching Pendamping Senior','Catatan pribadi Koordinator',`<div class="form-grid"><div><label class="label">Tanggal</label><input id="coachDate" type="date" value="${witaDate()}"></div><div><label class="label">Senior</label><select id="coachSenior">${opts.length?opts.map(x=>`<option>${esc(x)}</option>`).join(''):'<option value="">Nama belum tersedia</option>'}</select></div><div class="full"><label class="label">Topik</label><input id="coachTopic" value="Coaching Mingguan"></div><div class="full"><label class="label">Temuan/Fakta</label><textarea id="coachFinding" placeholder="Apa yang diamati? Hindari label atau asumsi."></textarea></div><div class="full"><label class="label">Arahan/Penguatan</label><textarea id="coachDirection" placeholder="Arahan yang diberikan kepada senior."></textarea></div><div><label class="label">Tindak lanjut sampai</label><input id="coachFollow" type="date"></div><div><label class="label">Status</label><select id="coachStatus"><option value="open">Terbuka</option><option value="done">Selesai</option></select></div></div><button class="btn primary full" onclick="saveCoaching()">Simpan Coaching</button><p class="privacy-note">Versi awal menyimpan log coaching secara pribadi pada browser/perangkat Koordinator. Data operasional Catar-Catir tetap berasal dari server MPK-PMB.</p>`)}
function saveCoaching(){const x={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:$('coachDate').value,senior:$('coachSenior').value,topic:$('coachTopic').value,finding:$('coachFinding').value,direction:$('coachDirection').value,followup:$('coachFollow').value,status:$('coachStatus').value};if(!x.senior)return toast('Pilih/isi nama senior terlebih dahulu.',true);state.coaching.push(x);saveLocal();closeModal();renderCoaching();toast('Coaching tersimpan.')}
function toggleCoach(id){const x=state.coaching.find(v=>v.id===id);if(!x)return;x.status=x.status==='done'?'open':'done';saveLocal();renderCoaching()}

function firstHome(){return state.groupHomes.values().next().value||null}
function renderAgenda(){const h=firstHome(),schedule=h?.schedule||[];$('agendaDay').textContent=`${DAYS[h?.day_of_week||'']} • ${fmtDate(state.date)}`;$('agendaSchedule').innerHTML=schedule.map(s=>`<div class="item"><div class="ico">${String(s.time_local||'').slice(0,5)}</div><div><b>${esc(s.activity_name)}</b><small>${esc(s.location||'')}${s.time_end?' • s.d. '+String(s.time_end).slice(0,5):''}</small></div><span class="badge">${s.managed_by==='kerohanian'?'Kerohanian':'MPK-PMB'}</span></div>`).join('')||'<div class="empty">Tidak ada jadwal.</div>';$('incidentalList').innerHTML=state.incidental.slice().sort((a,b)=>String(b.activity_date).localeCompare(String(a.activity_date))).slice(0,15).map(a=>`<div class="item"><div class="ico">★</div><div><b>${esc(a.title)}</b><small>${fmtDate(a.activity_date)}${a.location?' • '+esc(a.location):''}<br>${esc(a.activity_summary||'')}</small></div><span class="badge">${a.present_count||0}/${a.participant_total||0}</span></div>`).join('')||'<div class="empty">Belum ada kegiatan khusus/insidental.</div>'}
function openIncidentalForm(){openModal('Tambah Kegiatan Khusus / Insidental','Harus memiliki dasar/persetujuan sesuai Juklak',`<div class="form-grid"><div class="full"><label class="label">Nama Kegiatan</label><input id="incTitle"></div><div><label class="label">Tanggal</label><input id="incDate" type="date" value="${state.date}"></div><div><label class="label">Jenis</label><select id="incType"><option value="coaching">Pembinaan</option><option value="ceremonial">Seremonial</option><option value="academic">Akademik</option><option value="visit">Kunjungan</option><option value="community_service">Kerja Bakti/Sosial</option><option value="other">Lainnya</option></select></div><div><label class="label">Mulai</label><input id="incStart" type="time"></div><div><label class="label">Selesai</label><input id="incEnd" type="time"></div><div class="full"><label class="label">Lokasi</label><input id="incLocation"></div><div><label class="label">Cakupan</label><select id="incScope" onchange="incScopeChange()"><option value="all">Seluruh Catar-Catir</option>${GROUPS.map(g=>`<option value="${g.start}">${pad(g.start)}–${pad(g.end)} • ${g.supervisor}</option>`).join('')}</select></div><div><label class="label">Jumlah Peserta</label><input id="incTotal" type="number" value="80"></div><div class="full"><label class="label">Dasar/Persetujuan</label><input id="incApproval" placeholder="Arahan Direktur / persetujuan pimpinan"></div><div><label class="label">Hadir</label><input id="incPresent" type="number" value="80"></div><div><label class="label">Terlambat</label><input id="incLate" type="number" value="0"></div><div><label class="label">Izin</label><input id="incPermit" type="number" value="0"></div><div><label class="label">Sakit</label><input id="incSick" type="number" value="0"></div><div><label class="label">Tidak Hadir</label><input id="incAbsent" type="number" value="0"></div><div class="full"><label class="label">Ringkasan Pelaksanaan</label><textarea id="incSummary"></textarea></div><div class="full"><label class="label">Temuan</label><textarea id="incFindings"></textarea></div><div class="full"><label class="label">Tindak Lanjut</label><textarea id="incFollow"></textarea></div></div><button id="saveIncBtn" class="btn primary full" onclick="saveIncidental()">Simpan Kegiatan</button>`)}
function incScopeChange(){const v=$('incScope').value;if(v==='all'){$('incTotal').value=80;$('incPresent').value=80}else{const g=GROUPS.find(x=>x.start===Number(v)),n=g.end-g.start+1;$('incTotal').value=n;$('incPresent').value=n}}
async function saveIncidental(){const b=$('saveIncBtn');setBusy(b,true,'Menyimpan...');try{const scope=$('incScope').value,p={client_id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),activity_date:$('incDate').value,title:$('incTitle').value,activity_type:$('incType').value,time_start:$('incStart').value,time_end:$('incEnd').value,location:$('incLocation').value,participant_scope:scope==='all'?'all':'group',assignment_start:scope==='all'?null:Number(scope),responsible_person:state.coordName,approval_basis:$('incApproval').value,participant_total:Number($('incTotal').value||0),present_count:Number($('incPresent').value||0),late_count:Number($('incLate').value||0),permit_count:Number($('incPermit').value||0),sick_count:Number($('incSick').value||0),absent_count:Number($('incAbsent').value||0),activity_summary:$('incSummary').value,findings:$('incFindings').value,follow_up:$('incFollow').value,notes:''};if(!p.title||!p.activity_date||!p.activity_summary)throw new Error('Nama, tanggal, dan ringkasan kegiatan wajib diisi.');await incidentalApi('create',p);closeModal();toast('Kegiatan tersimpan.');const d=await incidentalApi('list');state.incidental=d.activities||[];renderAgenda()}catch(e){toast(e.message,true)}finally{setBusy(b,false,'Simpan Kegiatan')}}

function renderAssessment(){const a=state.exec?.assessments||{},cats=a.categories||[];$('assessmentCards').innerHTML=cats.length?cats.map(x=>`<div class="score-card"><strong>${Number(x.average||0).toFixed(2)}</strong><span>${esc(x.label)}</span><div class="progress"><i style="width:${clamp((Number(x.average||0)/10)*100,0,100)}%"></i></div></div>`).join(''):'<div class="empty">Data penilaian belum tersedia.</div>';const programs=a.programs||a.by_program||[];$('programScores').innerHTML=programs.length?programs.map(p=>`<div class="program-card"><b>${esc(p.program||p.label||p.name||'Program Studi')}</b>${Object.entries(p).filter(([k,v])=>typeof v==='number'&&k!=='participant_count').slice(0,5).map(([k,v])=>`<div class="score-mini"><span>${esc(k)}</span><b>${Number(v).toFixed(2)}</b></div>`).join('')}</div>`).join(''):'<div class="empty">Perbandingan per Prodi belum tersedia dari API.</div>'}

function renderIssues(){const ops=state.exec?.issues||[];$('allIssues').innerHTML=ops.map(issueHtml).join('')||'<div class="empty">Tidak ada isu operasional prioritas.</div>';const open=state.coaching.filter(x=>x.status!=='done');$('seniorFollowups').innerHTML=open.map(x=>`<div class="item"><div class="ico">C</div><div><b>${esc(x.senior)}</b><small>${esc(x.direction||x.finding||'')} ${x.followup?'<br>Batas: '+fmtDate(x.followup):''}</small></div><button class="badge warn" onclick="toggleCoach('${x.id}')">Tandai selesai</button></div>`).join('')||'<div class="empty">Tidak ada follow-up senior yang terbuka.</div>'}

function renderReport(){const e=state.exec||{},s=e.summary||{},a=s.attendance||{},cats=e.assessments?.categories||[],open=state.coaching.filter(x=>x.status!=='done');$('reportContent').innerHTML=`<h2>Laporan Ringkas Koordinator MPK-PMB</h2><p><b>Tanggal:</b> ${fmtDate(state.date)}<br><b>Koordinator:</b> ${esc(state.coordName)}</p><h4>1. Pelaksanaan</h4><p>Pelaksanaan kegiatan tercatat <b>${s.completion_pct||0}%</b>. Kegiatan belum tercatat: <b>${s.not_started||0}</b>.</p><h4>2. Kehadiran Catar-Catir</h4><p>Kehadiran: <b>${a.attendance_pct==null?'—':a.attendance_pct+'%'}</b>; terlambat ${a.late||0}; izin ${a.permit||0}; sakit ${a.sick||0}; tidak hadir ${a.absent||0}.</p><h4>3. Penilaian</h4><ul>${cats.map(x=>`<li>${esc(x.label)}: ${Number(x.average||0).toFixed(2)}</li>`).join('')||'<li>Belum ada data.</li>'}</ul><h4>4. Pendamping Senior</h4><p>Total struktur: 18 senior. Coaching pribadi tercatat ${state.coaching.length} sesi; ${open.length} tindak lanjut masih terbuka.</p><h4>5. Isu Prioritas</h4><ul>${(e.issues||[]).map(x=>`<li><b>${esc(x.title||'Isu')}</b> — ${esc(x.text||'')}</li>`).join('')||'<li>Tidak ada isu prioritas.</li>'}</ul><h4>6. Kegiatan Khusus</h4><p>${state.incidental.length} kegiatan khusus/insidental tersimpan pada daftar yang dapat diakses.</p><p class="privacy-note">Isi konseling individual BK tidak termasuk dalam laporan Koordinator ini.</p>`}

async function changePin(){const a=$('newPin1').value.trim(),b=$('newPin2').value.trim();if(!/^\d{6,12}$/.test(a))return toast('PIN baru harus 6–12 angka.',true);if(a!==b)return toast('Pengulangan PIN tidak sama.',true);const btn=$('changePinBtn');setBusy(btn,true,'Menyimpan...');try{await execApi('change_pin',{new_pin:a});state.pin=a;$('newPin1').value='';$('newPin2').value='';toast('PIN Koordinator berhasil diubah.')}catch(e){toast(e.message,true)}finally{setBusy(btn,false,'Ganti PIN')}}

function showTab(t){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));document.querySelectorAll('.tabview').forEach(x=>x.classList.add('hidden'));$(`tab-${t}`).classList.remove('hidden');if(t==='report')renderReport();if(t==='issues')renderIssues()}
function openModal(title,meta,body){$('modalTitle').textContent=title;$('modalMeta').textContent=meta||'';$('modalBody').innerHTML=body;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}

document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('loginBtn').onclick=login;$('loginPin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutBtn').onclick=logout;$('refreshBtn').onclick=loadAll;$('dateInput').onchange=loadAll;$('todayBtn').onclick=()=>{$('dateInput').value=witaDate();loadAll()};$('catarSearch').oninput=renderCatar;$('catarGroupFilter').onchange=renderCatar;$('newCoachingBtn').onclick=openCoachingForm;$('newIncidentalBtn').onclick=openIncidentalForm;$('printBtn').onclick=()=>window.print();$('changePinBtn').onclick=changePin;$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};
window.openGroup=openGroup;window.openCatar=openCatar;window.editSpecialSenior=editSpecialSenior;window.saveSpecialSenior=saveSpecialSenior;window.toggleCoach=toggleCoach;window.saveCoaching=saveCoaching;window.incScopeChange=incScopeChange;window.saveIncidental=saveIncidental;
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
init();
