plugins { id 'com.android.application' }

android {
    namespace 'com.fahriadipakaya.mpkpmb29'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fahriadipakaya.mpkpmb29'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
